Play travis
Otus-DevOps-2022-05/DiLysenk_microservices pull request #2
Opened 2022-08-18 20:19 UTC by DiLysenk

2022-08-22 13:14 UTC, mrgreyves requested changes
Здравствуйте!)
Оставил комментарий к файлу, дз возвращаю на доработку

2022-08-22 13:14 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 2)
Вот сюда смотрим внимательно и вносим исправления =)

2022-08-22 13:22 UTC, DiLysenk commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 2)
Так тут же все верно ^_^ не могу понять

2022-08-22 15:29 UTC, DiLysenk commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 2)
поправил расположение файлика auto_assign.yml

2022-08-23 13:34 UTC, mrgreyves commented on play-travis/test.py
> +        self.assertEqual(1 + 1, 2)
Уууупс, протупил =)

2022-08-23 13:35 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув ^_^

2022-08-23 15:28 UTC, merged